/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controlador.EquipoController;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexander
 */
public class GUIAdicionarEquipoRutina extends javax.swing.JFrame {    
    private final EquipoController equipoController = new EquipoController();


    /**
     * Creates new form GUIAdicionarNoPerecedero
     */
    public GUIAdicionarEquipoRutina() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrearRutina = new javax.swing.JButton();
        scrollPanelCrear = new javax.swing.JScrollPane();
        panelCrear = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        ftxtMarca = new javax.swing.JFormattedTextField();
        lblPrecio = new javax.swing.JLabel();
        ftxtEstado = new javax.swing.JFormattedTextField();
        lblCantidad = new javax.swing.JLabel();
        ftxtNRutina = new javax.swing.JFormattedTextField();
        lblCategoria = new javax.swing.JLabel();
        lblGarantia = new javax.swing.JLabel();
        ftxtRepeticiones = new javax.swing.JFormattedTextField();
        ftxtSeries = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar rutina");
        setResizable(false);

        btnCrearRutina.setBackground(new java.awt.Color(215, 13, 2));
        btnCrearRutina.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCrearRutina.setText("Crear");
        btnCrearRutina.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCrearRutina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearRutinaActionPerformed(evt);
            }
        });

        scrollPanelCrear.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPanelCrear.setPreferredSize(new java.awt.Dimension(400, 620));

        panelCrear.setPreferredSize(new java.awt.Dimension(400, 600));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombre.setText("Nombre");

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombre.setToolTipText("Nombre del producto");
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        lblCodigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCodigo.setText("Marca");

        ftxtMarca.setFormatterFactory(null);
        ftxtMarca.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        ftxtMarca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrecio.setText("Estado");

        ftxtEstado.setFormatterFactory(null);
        ftxtEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblCantidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCantidad.setText("Nombre Rutina");

        ftxtNRutina.setFormatterFactory(null);
        ftxtNRutina.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        ftxtNRutina.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblCategoria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCategoria.setText("Series");

        lblGarantia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGarantia.setText("Repeticiones");

        ftxtRepeticiones.setFormatterFactory(null);
        ftxtRepeticiones.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        ftxtRepeticiones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ftxtSeries.setFormatterFactory(null);
        ftxtSeries.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        ftxtSeries.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout panelCrearLayout = new javax.swing.GroupLayout(panelCrear);
        panelCrear.setLayout(panelCrearLayout);
        panelCrearLayout.setHorizontalGroup(
            panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCategoria)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(lblCodigo)
                    .addComponent(ftxtMarca)
                    .addComponent(lblPrecio)
                    .addComponent(ftxtEstado)
                    .addComponent(lblCantidad)
                    .addComponent(ftxtNRutina)
                    .addComponent(lblGarantia)
                    .addComponent(ftxtRepeticiones)
                    .addComponent(ftxtSeries))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        panelCrearLayout.setVerticalGroup(
            panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftxtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPrecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblCantidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftxtNRutina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ftxtSeries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblGarantia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ftxtRepeticiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        scrollPanelCrear.setViewportView(panelCrear);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPanelCrear, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(btnCrearRutina, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnCrearRutina)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearRutinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearRutinaActionPerformed
        // TODO add your handling code here:
    StringBuilder errores = new StringBuilder(); 

    if (txtNombre.getText().trim().isEmpty()) {
        errores.append("Debe llenar el campo Nombre\n");
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED));
    } else {
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY)); 
    }

    if (ftxtMarca.getText().trim().isEmpty()) {
        errores.append("Debe llenar el campo Marca\n");
        ftxtMarca.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED));
    } else {
        ftxtMarca.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY));
    }

    if (ftxtEstado.getText().trim().isEmpty()) {
        errores.append("Debe llenar el campo Estado\n");
        ftxtEstado.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED));
    } else {
        ftxtEstado.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY));
    }

    if (ftxtNRutina.getText().trim().isEmpty()) {
        errores.append("Debe llenar el campo Nombre Rutina\n");
        ftxtNRutina.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED));
    } else {
        ftxtNRutina.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY));
    }

    if (ftxtSeries.getText().trim().isEmpty()) {
        errores.append("Debe llenar el campo Series\n");
        ftxtSeries.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED));
    } else {
        ftxtSeries.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY));
    }

    if (ftxtRepeticiones.getText().trim().isEmpty()) {
        errores.append("Debe llenar el campo Repeticiones\n");
        ftxtRepeticiones.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED));
    } else {
        ftxtRepeticiones.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY));
    }

    // Si hay errores, los muestra todos juntos
    if (errores.length() > 0) {
        JOptionPane.showMessageDialog(null, errores.toString(), "Campos Vacíos", JOptionPane.ERROR_MESSAGE);
        return;
    }    
    
    String nombre = txtNombre.getText();
    String marca = ftxtMarca.getText();
    String estado = ftxtEstado.getText();
    String nombreRutina = ftxtNRutina.getText();
    double series = Double.parseDouble(ftxtSeries.getText());
    String repeticiones = ftxtRepeticiones.getText();
/*
    equipoController.insertarEquipoRutina(nombre, marca, estado, nombreRutina, series, repeticiones);
    JOptionPane.showMessageDialog(this, "Rutina agregada con éxito");
*/
    // Limpiar campos
    txtNombre.setText("");
    ftxtMarca.setText("");
    ftxtEstado.setText("");
    ftxtNRutina.setText("");
    ftxtSeries.setText("");
    ftxtRepeticiones.setText("");
    }//GEN-LAST:event_btnCrearRutinaActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearRutina;
    private javax.swing.JFormattedTextField ftxtEstado;
    private javax.swing.JFormattedTextField ftxtMarca;
    private javax.swing.JFormattedTextField ftxtNRutina;
    private javax.swing.JFormattedTextField ftxtRepeticiones;
    private javax.swing.JFormattedTextField ftxtSeries;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblGarantia;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JPanel panelCrear;
    private javax.swing.JScrollPane scrollPanelCrear;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
