/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controlador.EquipoController;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafa
 */
public class GUIAdicionarEquipoRutina extends javax.swing.JFrame {    
    private EquipoController equipoController = EquipoController.getInstancia();

    /**
     * Creates new form GUIAdicionarEquipoRutina
     */
    public GUIAdicionarEquipoRutina() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrearRutina = new javax.swing.JButton();
        scrollPanelCrear = new javax.swing.JScrollPane();
        panelCrear = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        ftxtMarca = new javax.swing.JFormattedTextField();
        lblPrecio = new javax.swing.JLabel();
        ftxtEstado = new javax.swing.JFormattedTextField();
        lblTipoEjercicio = new javax.swing.JLabel();
        ftxtNRutina = new javax.swing.JFormattedTextField();
        lblCategoria = new javax.swing.JLabel();
        lblGarantia = new javax.swing.JLabel();
        ftxtRepeticiones = new javax.swing.JFormattedTextField();
        ftxtSeries = new javax.swing.JFormattedTextField();
        lblCantidad1 = new javax.swing.JLabel();
        ftxtTEjercicio = new javax.swing.JFormattedTextField();
        lblTipoEjercicio1 = new javax.swing.JLabel();
        lblMaterial = new javax.swing.JLabel();
        ftxtPMax = new javax.swing.JFormattedTextField();
        ftxtMaterial = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar rutina");
        setResizable(false);

        btnCrearRutina.setBackground(new java.awt.Color(215, 13, 2));
        btnCrearRutina.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCrearRutina.setText("Crear");
        btnCrearRutina.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCrearRutina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearRutinaActionPerformed(evt);
            }
        });

        scrollPanelCrear.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPanelCrear.setPreferredSize(new java.awt.Dimension(400, 620));

        panelCrear.setPreferredSize(new java.awt.Dimension(400, 600));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombre.setText("Nombre");

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombre.setToolTipText("Nombre del producto");
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        lblCodigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCodigo.setText("Marca");

        ftxtMarca.setFormatterFactory(null);
        ftxtMarca.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        ftxtMarca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrecio.setText("Estado");

        ftxtEstado.setFormatterFactory(null);
        ftxtEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblTipoEjercicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTipoEjercicio.setText("Tipo de Ejercicio");

        ftxtNRutina.setFormatterFactory(null);
        ftxtNRutina.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        ftxtNRutina.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblCategoria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCategoria.setText("Series");

        lblGarantia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGarantia.setText("Repeticiones");

        ftxtRepeticiones.setFormatterFactory(null);
        ftxtRepeticiones.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        ftxtRepeticiones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ftxtSeries.setFormatterFactory(null);
        ftxtSeries.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        ftxtSeries.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblCantidad1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCantidad1.setText("Nombre Rutina");

        ftxtTEjercicio.setFormatterFactory(null);
        ftxtTEjercicio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblTipoEjercicio1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTipoEjercicio1.setText("Peso Maximo");

        lblMaterial.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaterial.setText("Material");

        ftxtPMax.setFormatterFactory(null);
        ftxtPMax.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ftxtMaterial.setFormatterFactory(null);
        ftxtMaterial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout panelCrearLayout = new javax.swing.GroupLayout(panelCrear);
        panelCrear.setLayout(panelCrearLayout);
        panelCrearLayout.setHorizontalGroup(
            panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCrearLayout.createSequentialGroup()
                        .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftxtTEjercicio, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftxtPMax, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftxtMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(346, Short.MAX_VALUE))
                    .addGroup(panelCrearLayout.createSequentialGroup()
                        .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(lblCodigo)
                            .addComponent(ftxtMarca)
                            .addComponent(lblPrecio)
                            .addComponent(ftxtEstado)
                            .addComponent(lblTipoEjercicio)
                            .addComponent(lblTipoEjercicio1)
                            .addComponent(lblMaterial))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCantidad1)
                            .addComponent(ftxtNRutina, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoria)
                            .addComponent(ftxtSeries, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGarantia)
                            .addComponent(ftxtRepeticiones, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57))))
        );
        panelCrearLayout.setVerticalGroup(
            panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblCantidad1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtNRutina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(lblCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtSeries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio)
                    .addComponent(lblGarantia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtRepeticiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblTipoEjercicio)
                .addGap(18, 18, 18)
                .addComponent(ftxtTEjercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTipoEjercicio1)
                .addGap(18, 18, 18)
                .addComponent(ftxtPMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMaterial)
                .addGap(18, 18, 18)
                .addComponent(ftxtMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        scrollPanelCrear.setViewportView(panelCrear);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPanelCrear, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                    .addComponent(btnCrearRutina, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btnCrearRutina)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearRutinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearRutinaActionPerformed
        // TODO add your handling code here:
    StringBuilder errores = new StringBuilder(); 

    if (txtNombre.getText().trim().isEmpty()) {
        errores.append("Debe llenar el campo Nombre\n");
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED));
    } else {
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY)); 
    }

    if (ftxtMarca.getText().trim().isEmpty()) {
        errores.append("Debe llenar el campo Marca\n");
        ftxtMarca.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED));
    } else {
        ftxtMarca.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY));
    }

    if (ftxtEstado.getText().trim().isEmpty()) {
        errores.append("Debe llenar el campo Estado\n");
        ftxtEstado.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED));
    } else {
        ftxtEstado.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY));
    }
    
    if (ftxtTEjercicio.getText().trim().isEmpty()) {
        errores.append("Debe llenar el campo Tipo Ejercicio\n");
        ftxtTEjercicio.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED));
    } else {
        ftxtTEjercicio.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY));
    }

    if (ftxtPMax.getText().trim().isEmpty()) {
        errores.append("Debe llenar el campo Peso Maximo\n");
        ftxtPMax.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED));
    } else {
        ftxtPMax.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY));
    }

    if (ftxtMaterial.getText().trim().isEmpty()) {
        errores.append("Debe llenar el campo Material\n");
        ftxtMaterial.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED));
    } else {
        ftxtMaterial.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY));
    }

    if (ftxtNRutina.getText().trim().isEmpty()) {
        errores.append("Debe llenar el campo Nombre Rutina\n");
        ftxtNRutina.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED));
    } else {
        ftxtNRutina.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY));
    }

    if (ftxtSeries.getText().trim().isEmpty()) {
        errores.append("Debe llenar el campo Series\n");
        ftxtSeries.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED));
    } else {
        ftxtSeries.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY));
    }

    if (ftxtRepeticiones.getText().trim().isEmpty()) {
        errores.append("Debe llenar el campo Repeticiones\n");
        ftxtRepeticiones.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.RED));
    } else {
        ftxtRepeticiones.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY));
    }

    // Si hay errores, los muestra todos juntos
    if (errores.length() > 0) {
        JOptionPane.showMessageDialog(null, errores.toString(), "Campos Vacíos", JOptionPane.ERROR_MESSAGE);
        return;
    }    
    
    try {
        String nombre = txtNombre.getText();
        String marca = ftxtMarca.getText();
        String estado = ftxtEstado.getText();
        String tipoDeEjercicio = ftxtTEjercicio.getText();
        double pesoMaximo = Double.parseDouble(ftxtPMax.getText());
        String material = ftxtMaterial.getText();
        String nombreRutina = ftxtNRutina.getText();
        int series = Integer.parseInt(ftxtSeries.getText().trim());
        int repeticiones = Integer.parseInt(ftxtRepeticiones.getText().trim());

        equipoController.insertarEquipoRutina(nombre, marca, estado, tipoDeEjercicio, pesoMaximo, material, nombreRutina, series, repeticiones);

        JOptionPane.showMessageDialog(this, "Rutina agregada con éxito");

        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error: Ingresa valores numéricos en Peso Máximo, Series y Repeticiones", "Error", JOptionPane.ERROR_MESSAGE);
    }

    // Limpiar campos
    txtNombre.setText("");
    ftxtMarca.setText("");
    ftxtEstado.setText("");
    ftxtTEjercicio.setText("");
    ftxtPMax.setText("");
    ftxtMaterial.setText("");
    ftxtNRutina.setText("");
    ftxtSeries.setText("");
    ftxtRepeticiones.setText("");
    
    
    }//GEN-LAST:event_btnCrearRutinaActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearRutina;
    private javax.swing.JFormattedTextField ftxtEstado;
    private javax.swing.JFormattedTextField ftxtMarca;
    private javax.swing.JFormattedTextField ftxtMaterial;
    private javax.swing.JFormattedTextField ftxtNRutina;
    private javax.swing.JFormattedTextField ftxtPMax;
    private javax.swing.JFormattedTextField ftxtRepeticiones;
    private javax.swing.JFormattedTextField ftxtSeries;
    private javax.swing.JFormattedTextField ftxtTEjercicio;
    private javax.swing.JLabel lblCantidad1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblGarantia;
    private javax.swing.JLabel lblMaterial;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTipoEjercicio;
    private javax.swing.JLabel lblTipoEjercicio1;
    private javax.swing.JPanel panelCrear;
    private javax.swing.JScrollPane scrollPanelCrear;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
